backend:
  name: github
  repo: xj596/aultrastea
  branch: main
  base_url: https://api.netlify.com
  auth_endpoint: auth

media_folder: static/images
public_folder: /images

# 最简功能，先确保后台能正常打开
collections:
  - name: "news"
    label: "新闻动态管理"
    folder: "news"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "新闻标题", name: "title", widget: "string", required: true}
      - {label: "发布日期", name: "date", widget: "datetime", required: true}
      - {label: "新闻正文", name: "body", widget: "markdown", required: true}
